# © Copyright IBM Corporation 2022
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
openapi: 3.0.0
info:
  description: This API provides access to customer account information
  version: 1.0.0
  title: Customer Account Information
  contact:
    email: apiteam@ibm.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  "/customers/{customerId}":
    get:
      summary: Find customer accounts by customer ID
      description: For valid response try integer IDs with 10 characters.
      operationId: getCustomerAccounts
      tags: 
        - Accounts
      parameters:
        - name: customerId
          in: path
          description: CustomerID for the accounts to be returned
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/customer"
servers:
  - url: http://restapi:8000
components:
  schemas:
    customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        accounts:
          type: object
          properties:
            savings:
              type: object
              properties:
                accountNumber:
                  type: string
                balance:
                  type: string
                status:
                  type: string
                lastTransaction:
                  type: string
                dateOpened:
                  type: string
            checking:
              type: object
              properties:
                accountNumber:
                  type: string
                balance:
                  type: string
                status:
                  type: string
                lastTransaction:
                  type: string
                dateOpened:
                  type: string
            loans:
              type: object
              properties:
                accountNumber:
                  type: string
                balance:
                  type: string
                status:
                  type: string
                lastTransaction:
                  type: string
                dateOpened:
                  type: string